### ISSUE TITLE
configuration screen too wide

### ISSUE THREAD

**Issue by robbo1975** [oliversturm/rsgb-emf-calculator-issues#1] opened 2021-12-06 21:09 UTC
The 'manage configuration' screen when opening and displaying configuration with detail next to it, scrolls off the side of a 1920x1080 resolution page.  The left most part of the configuration list starts almost half way across the screen. Reducing the size of the screen brings the content to the middle as expected, but since most people operate 'HD' resolution these days, it would be better to have this scale appropriately.

**To Reproduce**
1. Open application in Chrome browser
2. Expand to full screen
2. Click 'Configurations'
2. Select 'Manage'

**Expected behavior**
Content should show centrally  within the available viewing area within the browser

**Screenshots**
![image](https://user-images.githubusercontent.com/64151514/144922825-53914950-2bef-4fa6-bf82-1ca7f54a1e10.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome
 - Version: 96.0.4664.45 (Official Build) (64-bit)

**Application version (as displayed in the bottom right corner of the page):**
Version 1.0.12-beta1-11d

**Additional context**

**Comment by oliversturm** [comment] 2021-12-09 14:22
Many thanks for the report, and congrats on being the first reporter! It was surprisingly easy to reproduce this issue - a strange thing to happen. Will be fixed asap.

**Comment by oliversturm** [comment] 2021-12-09 15:02
The issue is fixed internally and the fix will be included in the next public release. You can see the change in the development preview of the app [at this link](https://oliversturm.github.io/rsgb-emf-calculator/).

**Closed as completed by oliversturm** 2021-12-09 15:02 UTC
Labels: just reported

**Comment by robbo1975** [comment] 2021-12-10 08:43
Good work Oliver, and thanks for responding so quickly
